// <auto-generated />
using System;
using EventIngestionAPI.Infrastructure.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventIngestionAPI.Infrastructure.Data.EntityFramework.Migrations
{
    [DbContext(typeof(MappingRuleContext))]
    [Migration("20251115231442_AddUniqueConstraintToExternalFieldCol")]
    partial class AddUniqueConstraintToExternalFieldCol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventIngestionAPI.Entities.MappingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ExternalField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InternalField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MappingRuleTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalField")
                        .IsUnique();

                    b.HasIndex("MappingRuleTypeId");

                    b.ToTable("MappingRules");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "playerId",
                            InternalField = "PlayerId",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "userId",
                            InternalField = "PlayerId",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "accountId",
                            InternalField = "PlayerId",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "amount",
                            InternalField = "Amount",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "value",
                            InternalField = "Amount",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -6,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "currency",
                            InternalField = "Currency",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -7,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "curr",
                            InternalField = "Currency",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -8,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "timestamp",
                            InternalField = "OccurredAt",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -9,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "occurredAt",
                            InternalField = "OccurredAt",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        },
                        new
                        {
                            Id = -10,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalField = "date",
                            InternalField = "OccurredAt",
                            IsActive = true,
                            MappingRuleTypeId = 1
                        });
                });

            modelBuilder.Entity("EventIngestionAPI.Entities.MappingRuleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MappingRuleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "default"
                        },
                        new
                        {
                            Id = 2,
                            Type = "dynamic"
                        });
                });

            modelBuilder.Entity("EventIngestionAPI.Entities.MappingRule", b =>
                {
                    b.HasOne("EventIngestionAPI.Entities.MappingRuleType", "MappingRuleType")
                        .WithMany()
                        .HasForeignKey("MappingRuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MappingRuleType");
                });
#pragma warning restore 612, 618
        }
    }
}
